### ISSUE TITLE
请教：[WinError 10061] No connection could be made because the target machine actively refused it'

### ISSUE THREAD

**Issue by P-Rainbow** [OhYee/documentDownloader#2]
作者您好！

在尝试运行您所给出的示例代码时，我遇到了如下的错误信息。

能否请您给出相关建议？谢谢！

python main.py -i https://max.book118.com/html/2020/0109/5301014320002213.shtm -o '单身人群专题研究报告-2019.pdf' -p http://127.0.0.1:1080 -f -t 20

Proxy has been set http://127.0.0.1:1080
Get page error: HTTPSConnectionPool(host='max.book118.com', port=443): Max retries exceeded with url: /index.php?g=Home&m=View&a=ViewUrl&cid=5301014320002213&flag=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x035B5940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))), 10 times left...

Retry 10次完毕后，出错信息为“Can not get the page https://max.book118.com/index.php”。

**Comment by OhYee** [comment]
@NedLi 
大概是你的电脑没有在1080端口启动代理服务（这个主要是考虑到如果一个电脑短时间大量下载会被服务器暂时拉黑）

`-p` 部分设置的是代理地址，如果不需要设置代理可以不使用`-p`选项
程序会默认使用`http_proxy`和`https_proxy`两个作为代理，如果有设置`-p`参数，则会使用其设置的代理替换默认代理。如果上述都未设置，则会直连对应的页面

可以试下这样直连下载
```bash
python main.py -i https://max.book118.com/html/2020/0109/5301014320002213.shtm -o '单身人群专题研究报告-2019.pdf' -f -t 20
```

**Comment by P-Rainbow** [comment]
非常感谢作者@OhYee热情迅速细致的回复！

再次尝试，代码运行良好。只是可能因为网络的问题，尚未能顺利完全下载。

Get page error: HTTPSConnectionPool(host='max.book118.com', port=443): Max retries exceeded with url: /index.php?g=Home&m=View&a=ViewUrl&cid=5301014320002213&flag=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x039E56B8>, 'Connection to max.book118.com timed out. (connect timeout=10)')), 10 times left...
Get page error: HTTPSConnectionPool(host='view44.book118.com', port=443): Read timed out. (read timeout=10), 10 times left...
Get page error: HTTPSConnectionPool(host='view44.book118.com', port=443): Read timed out. (read timeout=10), 9 times left...
Get page error: HTTPSConnectionPool(host='view44.book118.com', port=443): Read timed out. (read timeout=10), 8 times left...
Get image url 1/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXeYJUnaglHcLE9Vk_9nCXmDg=
Get image url 2/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXeXFxjrInr4eM9ru8OdJQYak=
Get image url 3/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXeaFv5khBwoQnakR6euhZHZ8=
Get image url 4/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXebF3oaRqxE1aD5fdtmy4EsQ=
Get image url 5/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXebGbKte86_SjP50n5rhY4FU=
Get image url 6/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXeWcfKIqatfO5X6qDqszFclw=
Get image url 7/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXeT3wWMX7fgCmTKV@cukkE_4=
Get image url 8/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXeSpZmAwv2F2oyJZdnC_I4Nk=
Get image url 9/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXeSnueCZFSxSsEUxrTXJYRu0=
Get image url 10/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXeRxnryBa_2yCNln0iXfvHK0=
Get image url 11/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXeaoi0I4mwbo4WLnGa2_vH3I=
Get image url 12/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXeb7lLyOkk_nD6fNjnwau5L4=
Get image url 13/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXebnf6gvbvjSMv@D8XVCBRwM=
Get image url 14/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXeeSN0GB95pcGbeFOY8QR@t8=
Get page error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)), 10 times left...
Get image url 15/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXeb3SRfHSwG9UGKbEKnCDzr4=
Get image url 16/24 7o@o7xcocmkRaCbr5LmGeCVV6ATOYBBte8WGyWRAq1sKZ55snHCXeQNz_0PD54sNlAGZbOrncTg=
Get page error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)), 10 times left...
Get page error: HTTPSConnectionPool(host='view44.book118.com', port=443): Read timed out. (read timeout=10), 9 times left...
Get page error: HTTPSConnectionPool(host='view44.book118.com', port=443): Read timed out. (read timeout=10), 8 times left...
Get page error: HTTPSConnectionPool(host='view44.book118.com', port=443): Read timed out. (read timeout=10), 7 times left...
Get page error: HTTPSConnectionPool(host='view44.book118.com', port=443): Read timed out. (read timeout=10), 6 times left...
Get page error: HTTPSConnectionPool(host='view44.book118.com', port=443): Read timed out. (read timeout=10), 5 times left...
Get page error: HTTPSConnectionPool(host='view44.book118.com', port=443): Read timed out. (read timeout=10), 4 times left...
Get page error: HTTPSConnectionPool(host='view44.book118.com', port=443): Read timed out. (read timeout=10), 3 times left...
Get page error: HTTPSConnectionPool(host='view44.book118.com', port=443): Read timed out. (read timeout=10), 2 times left...
Get page error: HTTPSConnectionPool(host='view44.book118.com', port=443): Read timed out. (read timeout=10), 1 times left...
Can not get the page https://view44.book118.com/PW/GetPage/?

**Comment by OhYee** [comment]
网络的话，可以试试修改下 request.py 中的请求函数，把超时时间调长一点（比如60秒）
也可以试试换成手机热点下载

网络热点比较玄学，不一定为啥。没别的问题的话就关掉这个issue吧

**Comment by P-Rainbow** [comment]
再次感谢作者@OhYee的指导！
